package ADT.Enums;

public enum EnumCharacters {
    ESTRUCTURA_AEREO,
    ESTRUCTURA_BLOQUE,
    ESTRUCTURA_IMPACTO,
    ESTRUCTURA_CONTACTO,
    ESTRUCTURA_MEDIO_ALCANCE,
    ESTRUCTURA_ATAQUE_MULTIPLE,
    ZOMBIE_AEREO,
    ZOMBIE_IMPACTO,
    ZOMBIE_CONTACTO,
    ZOMBIE_MEDIO_ALCANCE
}
